export const DEMO_SCHEDULE = {
  scheduleId: 'demo-schedule-1',
  clubId: 'demo-club',
  sessions: [
    {
      id: 'sess-1',
      dayOfWeek: 1,
      startTime: '10:00',
      endTime: '11:00',
      trainerId: 'trainer-1',
      trainerName: 'Max Mustermann',
      groupIds: ['group-1'],
      groupNames: ['Anfänger'],
      maxParticipants: 4,
      notes: 'Einsteiger',
    },
    {
      id: 'sess-2',
      dayOfWeek: 3,
      startTime: '14:00',
      endTime: '15:30',
      trainerId: 'trainer-2',
      trainerName: 'Anna Schmidt',
      groupIds: ['group-2'],
      groupNames: ['Fortgeschrittene'],
      maxParticipants: 6,
      notes: 'intensiv',
    },
    {
      id: 'sess-3',
      dayOfWeek: 5,
      startTime: '16:00',
      endTime: '17:00',
      trainerId: 'trainer-1',
      trainerName: 'Max Mustermann',
      groupIds: ['group-1', 'group-2'],
      groupNames: ['Anfänger', 'Fortgeschrittene'],
      maxParticipants: 8,
      notes: 'Mixed',
    },
  ],
};
