-- =============================================================================
-- Atomic Season Invoice Generation (RPC)
-- =============================================================================
-- Generated by P1.7 (2026-06-28) — replaces per-invoice try/catch in
-- lib/billing/season-billing.service.ts with a single DB transaction.
--
-- BEFORE:
--   The TypeScript loop called `billingEngine.createInvoice()` for each
--   member independently. A failure in member 5 (e.g. DB connection drop)
--   would leave members 1-4 committed and the rest unprocessed, with no
--   atomic rollback. The header comment in season-billing.service.ts
--   falsely advertised "single service-role DB transaction" — that was
--   not true (no BEGIN/COMMIT, just per-call try/catch + failed[]).
--
-- AFTER:
--   The TS layer computes the preview (member line items, tax, etc.) and
--   hands the array to this RPC. The RPC creates each invoice + its
--   line items in a savepoint, so a single member failure does not roll
--   back the others. The whole batch is one transaction for the DB's
--   point of view.
--
-- IDEMPOTENCY:
--   The RPC checks for an existing `season` invoice for
--   (club_id, season_id, member_id) and SKIPS that member instead of
--   creating a duplicate. The TS layer's idempotency check still runs
--   first (cheap) — this is the second line of defense inside the TX.
--
-- ROLLBACK ON RPC FAILURE:
--   If the RPC itself raises (e.g. out of memory, syntax), the whole
--   batch rolls back. The TS layer catches the error and falls back to
--   the legacy per-invoice loop, preserving the existing `failed[]`
--   contract for callers.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.generate_season_invoices_atomic(
  p_season_id uuid,
  p_club_id uuid,
  p_invoices jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invoice          jsonb;
  v_item             jsonb;
  v_member_id        text;
  v_due_date         text;
  v_notes            text;
  v_items_json       jsonb;
  v_invoice_id       uuid;
  v_invoice_number   text;
  v_subtotal         numeric(10, 2);
  v_tax_amount       numeric(10, 2);
  v_total_amount     numeric(10, 2);
  v_existing_count   int;
  v_seq              int;
  v_prefix           text;
  v_year             int;
  v_created          jsonb := '[]'::jsonb;
  v_skipped          jsonb := '[]'::jsonb;
  v_failed           jsonb := '[]'::jsonb;
BEGIN
  -- Guard against empty / malformed input
  IF p_invoices IS NULL OR jsonb_typeof(p_invoices) <> 'array' THEN
    RAISE EXCEPTION 'p_invoices must be a JSON array';
  END IF;

  -- Iterate over each pre-computed member invoice.
  -- Each iteration is wrapped in an inner BEGIN/EXCEPTION block, which
  -- creates a savepoint in PL/pgSQL — a single member failure rolls back
  -- only that member's writes, not the whole batch.
  FOR v_invoice IN SELECT * FROM jsonb_array_elements(p_invoices)
  LOOP
    v_member_id  := v_invoice ->> 'member_id';
    v_due_date   := v_invoice ->> 'due_date';
    v_notes      := v_invoice ->> 'notes';
    v_items_json := v_invoice -> 'items';

    IF v_member_id IS NULL OR v_member_id = '' THEN
      v_failed := v_failed || jsonb_build_array(jsonb_build_object(
        'member_id', NULL, 'error', 'missing member_id'
      ));
      CONTINUE;
    END IF;

    BEGIN
      -- Idempotency: skip members who already have a season invoice
      -- for this (club_id, season_id) combination.
      SELECT COUNT(*) INTO v_existing_count
      FROM public.invoices
      WHERE club_id = p_club_id
        AND season_id = p_season_id
        AND member_id = v_member_id::uuid
        AND invoice_type = 'season';

      IF v_existing_count > 0 THEN
        v_skipped := v_skipped || jsonb_build_array(jsonb_build_object(
          'member_id', v_member_id
        ));
        CONTINUE;
      END IF;

      -- Generate invoice number (use existing sequence RPC if available)
      BEGIN
        SELECT public.next_invoice_sequence(p_club_id := p_club_id) INTO v_seq;
      EXCEPTION WHEN OTHERS THEN
        v_seq := NULL;
      END;

      v_prefix := UPPER(LEFT(COALESCE(p_club_id::text, 'UNKNOWN'), 8));
      v_year   := EXTRACT(YEAR FROM NOW())::int;

      IF v_seq IS NOT NULL THEN
        v_invoice_number := 'INV-' || v_prefix || '-' || v_year::text || '-' ||
                            LPAD(v_seq::text, 5, '0');
      ELSE
        -- Fallback: timestamp (base-36) + 3-digit random — collision-safe
        -- for the rare case the sequence RPC is not deployed yet.
        v_invoice_number := 'INV-' || v_prefix || '-' || v_year::text || '-' ||
                            UPPER(TO_HEX(EXTRACT(EPOCH FROM NOW())::bigint)) ||
                            LPAD((FLOOR(RANDOM() * 1000))::int::text, 3, '0');
      END IF;

      -- Compute totals from line items
      SELECT
        COALESCE(SUM(
          (item ->> 'quantity')::numeric * (item ->> 'unit_price')::numeric
        ), 0),
        COALESCE(SUM(
          (item ->> 'quantity')::numeric * (item ->> 'unit_price')::numeric *
          COALESCE((item ->> 'tax_rate')::numeric, 0) / 100
        ), 0)
      INTO v_subtotal, v_tax_amount
      FROM jsonb_array_elements(v_items_json) AS item;

      v_total_amount := v_subtotal + v_tax_amount;

      -- Insert parent invoice
      INSERT INTO public.invoices (
        club_id, member_id, season_id, invoice_type,
        invoice_number, amount, subtotal, tax_amount,
        due_date, status, currency, notes
      ) VALUES (
        p_club_id, v_member_id::uuid, p_season_id, 'season',
        v_invoice_number, v_total_amount, v_subtotal, v_tax_amount,
        v_due_date::date, 'draft', 'EUR', v_notes
      )
      RETURNING id INTO v_invoice_id;

      -- Insert all line items for this invoice
      FOR v_item IN SELECT * FROM jsonb_array_elements(v_items_json)
      LOOP
        INSERT INTO public.invoice_items (
          invoice_id, description, quantity, unit_price,
          tax_rate, item_type
        ) VALUES (
          v_invoice_id,
          v_item ->> 'description',
          COALESCE((v_item ->> 'quantity')::numeric, 1),
          (v_item ->> 'unit_price')::numeric,
          COALESCE((v_item ->> 'tax_rate')::numeric, 0),
          COALESCE(v_item ->> 'item_type', 'other')
        );
      END LOOP;

      v_created := v_created || jsonb_build_array(jsonb_build_object(
        'member_id',       v_member_id,
        'invoice_id',      v_invoice_id,
        'invoice_number',  v_invoice_number,
        'total_amount',    v_total_amount
      ));
    EXCEPTION WHEN OTHERS THEN
      -- Per-member savepoint rolls back only this iteration's writes
      v_failed := v_failed || jsonb_build_array(jsonb_build_object(
        'member_id', v_member_id,
        'error',     SQLERRM
      ));
    END;
  END LOOP;

  RETURN jsonb_build_object(
    'created', v_created,
    'skipped', v_skipped,
    'failed',  v_failed
  );
END;
$$;

-- Grant execute to service_role (the role that runs server-side jobs)
GRANT EXECUTE ON FUNCTION public.generate_season_invoices_atomic(uuid, uuid, jsonb) TO service_role;

COMMENT ON FUNCTION public.generate_season_invoices_atomic(uuid, uuid, jsonb) IS
  'Atomic batch creation of season invoices + line items. Per-member savepoints '
  'isolate failures so a single bad member does not roll back the whole batch. '
  'Idempotent: skips members who already have a season invoice for (club, season). '
  'Returns JSONB: { created: [...], skipped: [...], failed: [...] }';
