/**
 * tests/bench/bench-types.ts
 *
 * Shared type definitions for the bench → report pipeline.
 *
 * Exports:
 *   - BenchEntry   — one run (label + optional metrics). The `runs` map keys.
 *   - BenchReport  — the JSON envelope wrapping `runs: Record<string, BenchEntry>`.
 *   - BenchConfig  — NUM_MEMBERS / NUM_TRAINERS / NUM_COURTS shape.
 *
 * Imported by:
 *   - tests/bench/clustering.bench.ts                 (writer, vitest bench)
 *   - tests/e2e/clustering-performance.spec.ts        (writer, Playwright E2E)
 *   - scripts/generate-perf-report.ts                 (reader, generates Markdown)
 *
 * Why this file exists
 * ─────────────────────
 * The writers (`clustering.bench.ts` and `clustering-performance.spec.ts`)
 * used untyped `Record<string, any>` indexes or local `interface BenchEntry`
 * duplicates that drifted from the reader (`generate-perf-report.ts`), which
 * let them add fields the reader never consumed.
 * Three such fields accumulated as dead code:
 *   - `runtimeMs_internal`   (removed in Sprint 4 cleanup; `_internal` suffix)
 *   - `iterations_internal`  (removed in Sprint 4 cleanup; `_internal` suffix)
 *   - `iterations: 1`        (removed in this same refactor; NO suffix —
 *                             always hardcoded to 1 because vitest's `bench()`
 *                             already averages internally)
 *
 * With this shared interface, `BENCH_RESULTS: Record<string, BenchEntry>`
 * triggers TypeScript's excess-property check on every assignment. A writer
 * that adds a typo'd or dead-code field now fails at compile time, not in
 * production. Renames or removals on the reader side also break the writer
 * immediately.
 *
 * Field provenance is documented inline so future contributors know which
 * pipeline stage produces which field.
 */

export interface BenchConfig {
  /** Number of members in the simulated club. */
  NUM_MEMBERS: number;
  /** Number of trainers in the simulated club. */
  NUM_TRAINERS: number;
  /** Number of courts in the simulated club. */
  NUM_COURTS: number;
}

export interface BenchEntry {
  /** Unique run label (writer-defined). The only field both writer and reader rely on unconditionally. */
  label: string;

  // ─── Writer: vitest bench (tests/bench/clustering.bench.ts) ──────────
  /** ISO timestamp of when the run was recorded. */
  timestamp?: string;
  /** Engine-only mean runtime in ms (no HTTP / DB / network overhead). */
  meanMs?: number;
  /** Engine-only min runtime in ms. */
  minMs?: number;
  /** Engine-only max runtime in ms. */
  maxMs?: number;

  // ─── Writer: Playwright E2E (tests/e2e/clustering-performance.spec.ts) ─
  /** Run status. Only the two values actually produced by the writers. */
  status?: 'ok' | 'error';
  /** Full HTTP round-trip in ms (including network + auth overhead). */
  endToEndMs?: number;
  /** Server-side engine time in ms (no network, but includes auth + DB). */
  apiRuntimeMs?: number;
  /** Error message if the run failed. */
  error?: string;

  // ─── Both writers ────────────────────────────────────────────────────
  /** Number of training groups generated by the engine. */
  totalGroups?: number;
  /** Total members processed by the engine. */
  totalMembers?: number;
  /** Average niveau-match percentage (0–100). */
  avgNiveauMatch?: number;
  /** Members the engine could not assign. */
  unassignedCount?: number;
  /** Percentage (0–100) of wish-partner pairs honoured. */
  wishPartnerRate?: number;
  /** Config used for this run. */
  config?: BenchConfig;
}

/**
 * Envelope around the `runs` map. Written by both:
 *   - tests/bench/clustering.bench.ts (vitest bench)
 *   - tests/e2e/clustering-performance.spec.ts (Playwright E2E)
 * Read by scripts/generate-perf-report.ts.
 *
 * Only `runs` is required — every other field is optional because the two
 * writers produce different metadata (e.g., `baseUrl` + `runType` are E2E-
 * only, `platform` is bench-only). The reader handles missing fields via
 * `??` fallbacks.
 */
export interface BenchReport {
  /** Map of run-label → entry. Required. */
  runs: Record<string, BenchEntry>;

  // ─── Common (both writers) ─────────────────────────────────────────
  /** ISO timestamp of when the report file was written. */
  generatedAt?: string;
  /** Node.js version that produced this report (e.g. 'v24.15.0'). */
  nodeVersion?: string;
  /** Config used for the simulated club (NUM_MEMBERS, NUM_TRAINERS, NUM_COURTS). */
  config?: BenchConfig;

  // ─── Writer: vitest bench only ─────────────────────────────────────
  /** Platform string (e.g. 'linux/x64') — only the bench file writes this. */
  platform?: string;

  // ─── Writer: Playwright E2E only ───────────────────────────────────
  /** Base URL of the dev server the E2E run hit (e.g. 'http://localhost:3000'). */
  baseUrl?: string;
  /** Run-type discriminator (e.g. 'e2e-playwright') — set by the E2E writer. */
  runType?: string;
  /** Pre-computed speedup map (label → 'Nx' string) — the E2E writer emits this
   *  to avoid re-computing on every report render. Optional. */
  speedups?: Record<string, string>;
}
